// clientValue — SSR-safe reads of browser-only values, without setState-in-effect.
// Synced automatically by type-tools/scripts/sync-sites.mjs.
// DO NOT edit this file inside a submodule — edit type-tools/shared/lib/clientValue.ts instead.
//
// The demos need browser facts that do not exist during SSR: pointer capability, sensor
// availability, Web Speech support. The obvious approach — useState(false) plus an effect that
// calls setState after mount — triggers a cascading render and is flagged by
// react-hooks/set-state-in-effect. useSyncExternalStore is React's sanctioned answer: it reads
// the value during render on the client, uses the server snapshot during SSR and hydration, and
// never schedules an extra render pass.

import { useSyncExternalStore } from 'react'

/** Subscribe that never fires — for values fixed for the lifetime of the page. */
const NEVER_CHANGES = () => () => {}

/**
 * Read a browser-only value that cannot change after load (feature detection, sensor presence).
 *
 * @param read         - Evaluated on the client during render. Must not touch the DOM tree.
 * @param serverValue  - Returned during SSR and hydration; pick the safe "not available" default.
 */
export function useClientValue<T>(read: () => T, serverValue: T): T {
	return useSyncExternalStore(NEVER_CHANGES, read, () => serverValue)
}

/**
 * Track a CSS media query, updating if it changes (viewport resize, device rotation,
 * plugging in a mouse). Returns false during SSR and hydration.
 */
export function useMediaQuery(query: string): boolean {
	return useSyncExternalStore(
		(onChange) => {
			const mql = window.matchMedia(query)
			mql.addEventListener('change', onChange)
			return () => mql.removeEventListener('change', onChange)
		},
		() => window.matchMedia(query).matches,
		() => false,
	)
}
