// Canonical tool colour system for all type-tools sites.
// Computation lives in toolColorsCore.mjs (single source of truth shared with sync-sites.mjs).
// Synced automatically by type-tools/scripts/sync-sites.mjs.
// DO NOT edit this file inside a submodule — edit type-tools/shared/lib/toolColors.ts instead.

// Types provided by toolColorsCore.d.mts (synced alongside this file).
import { toolBg, toolBtnBg, toolFg, toolFgMuted, toolFgSubtle, toolFgFaint, toolPanel } from './toolColorsCore.mjs'

/** All tool IDs in canonical order. Must match TOOL_IDS in toolColorsCore.mjs. */
export const TOOL_IDS = [
	'axisRhythm',
	'fitFlush',
	'fitWidth',
	'floodText',
	'glyphShaper',
	'hoverBoldly',
	'magnetType',
	'opszStepper',
	'opticalMargin',
	'ragtooth',
	'speechType',
	'stabilType',
	'steadyGray',
	'textBreath',
	'typsettle',
	'vfClamp',
	'wrapType',
	'threadText',
] as const

export type ToolId = typeof TOOL_IDS[number]

export { toolBg, toolBtnBg, toolFg, toolFgMuted, toolFgSubtle, toolFgFaint, toolPanel }
