// CookieBanner — GDPR cookie consent banner for GA4 Consent Mode v2.
// Synced automatically by type-tools/scripts/sync-sites.mjs.
// DO NOT edit this file inside a submodule — edit type-tools/shared/components/CookieBanner.tsx instead.

'use client'

import { useSyncExternalStore } from 'react'

const STORAGE_KEY = 'cookie-consent'

/**
 * Sentinel returned during SSR and hydration. Any non-null snapshot hides the banner, so the
 * server never renders it — matching the previous behaviour where the banner appeared only
 * after mount. Prevents a flash of the banner for visitors who already chose.
 */
const SSR_SNAPSHOT = 'ssr'

/** Sentinel for blocked storage (Safari private mode, embedded webviews) — stays hidden. */
const BLOCKED_SNAPSHOT = 'blocked'

/** Subscribers to consent changes. localStorage has no same-tab change event, so writes notify here. */
const listeners = new Set<() => void>()

/** Notify every mounted banner that the stored consent value changed. */
function emitConsentChange(): void {
	listeners.forEach((l) => l())
}

/**
 * Subscribe to consent changes: local writes via the listener set, other tabs via `storage`.
 * Returns the unsubscribe function required by useSyncExternalStore.
 */
function subscribe(onStoreChange: () => void): () => void {
	listeners.add(onStoreChange)
	window.addEventListener('storage', onStoreChange)
	return () => {
		listeners.delete(onStoreChange)
		window.removeEventListener('storage', onStoreChange)
	}
}

/**
 * Current consent value, or null when the visitor has not chosen yet (the only state that
 * shows the banner). Returns a primitive so useSyncExternalStore's identity check is stable.
 */
function getSnapshot(): string | null {
	try {
		return localStorage.getItem(STORAGE_KEY)
	} catch {
		return BLOCKED_SNAPSHOT
	}
}

/** Server snapshot — always non-null so the banner is never server-rendered. */
function getServerSnapshot(): string {
	return SSR_SNAPSHOT
}

/** Persist a consent choice and notify subscribers so the banner re-reads and hides. */
function persistConsent(value: 'granted' | 'denied'): void {
	try { localStorage.setItem(STORAGE_KEY, value) } catch { /* storage blocked — choice is session-only */ }
	emitConsentChange()
}

/** Cookie consent banner. Shows once per browser; persists choice to localStorage. */
export default function CookieBanner() {
	// Derived straight from the external store — no effect, so no cascading render on mount.
	const consent = useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot)
	const visible = consent === null

	function grant() {
		persistConsent('granted')
		// Update GA4 Consent Mode v2 for the current session if already loaded
		if (typeof (window as unknown as Window & { gtag?: (...args: unknown[]) => void }).gtag === 'function') {
			(window as unknown as Window & { gtag: (...args: unknown[]) => void }).gtag(
				'consent', 'update', { analytics_storage: 'granted' }
			)
		}
	}

	function deny() {
		persistConsent('denied')
	}

	if (!visible) return null

	return (
		<div
			role="dialog"
			aria-label="Cookie consent"
			// Fixed dark overlay (consistent across all tools) — uses fixed light text, not theme
			// vars, so it stays legible on both dark- and light-background sites.
			className="fixed bottom-0 left-0 right-0 z-50 border-t border-white/10 bg-black/90 backdrop-blur-sm px-4 py-3 flex flex-col sm:flex-row items-center gap-3 text-xs text-white"
		>
			<p className="flex-1 text-white/70">
				This site uses Google Analytics to understand how visitors use it. No personal data is shared beyond standard GA4 defaults.
			</p>
			<div className="flex gap-4 shrink-0">
				<button onClick={deny} className="px-3 py-1.5 rounded text-white/70 hover:text-white hover:bg-white/10 transition-colors">
					Decline
				</button>
				<button
					onClick={grant}
					className="px-3 py-1.5 rounded bg-white/15 text-white hover:bg-white/25 transition-colors"
				>
					Accept
				</button>
			</div>
		</div>
	)
}
