// SiteHeader — shared sticky header for all type-tools sites.
// Synced automatically by type-tools/scripts/sync-sites.mjs.
// DO NOT edit this file inside a submodule — edit type-tools/shared/components/SiteHeader.tsx instead.
//
// The header makes the FAMILY the product: a "Type Tools ▾" menu drops the full tool grid so a
// visitor can jump to any sibling from the top of any page. Left: the tool's wordmark. Right:
// optional per-tool section anchors, the family switcher, and npm / GitHub for the current tool.
// Themed per-tool via the family colour tokens, exactly like SiteFooter.
'use client'

import { useState } from 'react'
import Link from 'next/link'
import ToolDirectory, { TOOLS } from './ToolDirectory'

/** A per-tool in-page section anchor (e.g. cedars: Analyzer / Discover / Engine). */
interface Section {
	label: string
	href: string
}

interface SiteHeaderProps {
	/** ID of the current tool — highlights it in the family menu, derives the wordmark. */
	current: string
	/** Optional in-page section links shown before the family switcher. */
	sections?: Section[]
	/** Optional npm package URL for the current tool. */
	npmUrl?: string
	/** Optional GitHub repo URL for the current tool. */
	githubUrl?: string
	/** Optional wordmark override (defaults to the tool's name from the directory). */
	wordmark?: string
}

/** Shared sticky header: wordmark, section anchors, a family switcher, and npm/GitHub. */
export default function SiteHeader({ current, sections = [], npmUrl, githubUrl, wordmark }: SiteHeaderProps) {
	const [open, setOpen] = useState(false)
	const name = wordmark ?? TOOLS.find((t) => t.id === current)?.name ?? current

	return (
		<header
			className="sticky top-0 z-50 w-full border-b border-foreground/10"
			style={{ background: 'color-mix(in srgb, var(--background) 82%, transparent)', backdropFilter: 'saturate(140%) blur(10px)' }}
			onMouseLeave={() => setOpen(false)}
		>
			{/* px-6 wraps OUTSIDE the max-w container to match <main> in every page.tsx —
			    padding inside the container would inset the wordmark 24px further than the
			    body copy below it. The wrapper keeps border-b spanning the full width. */}
			<div className="w-full px-6">
				<div className="mx-auto w-full max-w-2xl lg:max-w-5xl h-14 flex items-center justify-between gap-6">
					<Link href="/" className="text-lg font-semibold tracking-tight" style={{ fontFamily: 'var(--font-merriweather, Merriweather, serif)', color: 'var(--foreground)' }}>
						{name}
					</Link>

					<nav className="flex items-center gap-5 text-sm" style={{ color: 'var(--foreground-muted)' }}>
						{sections.map((s) => (
							<a key={s.href} href={s.href} className="hidden sm:inline hover:text-[var(--foreground)]" style={{ color: 'inherit', textDecoration: 'none' }}>
								{s.label}
							</a>
						))}

						{/* Family switcher — the meaningful core: jump to any sibling from anywhere. */}
						<button
							type="button"
							aria-expanded={open}
							aria-haspopup="true"
							onClick={() => setOpen((o) => !o)}
							className="inline-flex items-center gap-1 hover:text-[var(--foreground)]"
							style={{ color: open ? 'var(--foreground)' : 'inherit', background: 'none', border: 'none', font: 'inherit', cursor: 'pointer' }}
						>
							Type Tools <span style={{ fontSize: '0.8em', transform: open ? 'rotate(180deg)' : 'none', transition: 'transform 0.15s' }}>▾</span>
						</button>

						{npmUrl && (
							<a href={npmUrl} target="_blank" rel="noreferrer" className="hidden sm:inline hover:text-[var(--foreground)]" style={{ color: 'inherit', textDecoration: 'none' }}>
								npm ↗
							</a>
						)}
						{githubUrl && (
							<a href={githubUrl} target="_blank" rel="noreferrer" className="hover:text-[var(--foreground)]" style={{ color: 'inherit', textDecoration: 'none' }}>
								GitHub ↗
							</a>
						)}
					</nav>
				</div>
			</div>

			{/* Family panel — reuses the ToolDirectory grid (all tools, current highlighted). */}
			{open && (
				<div className="border-t border-foreground/10" style={{ background: 'var(--background)' }}>
					<div className="w-full px-6">
						<div className="mx-auto w-full max-w-2xl lg:max-w-5xl py-7">
							<p className="text-xs uppercase tracking-widest mb-4" style={{ color: 'var(--foreground-faint)' }}>The Type Tools family</p>
							<ToolDirectory current={current} />
						</div>
					</div>
				</div>
			)}
		</header>
	)
}
