// SiteFooter — shared footer for all type-tools sites.
// Synced automatically by type-tools/scripts/sync-sites.mjs.
// DO NOT edit this file inside a submodule — edit type-tools/shared/components/SiteFooter.tsx instead.

import Script from 'next/script'
import ToolDirectory from "./ToolDirectory"
import CookieBanner from "./CookieBanner"

interface SiteFooterProps {
	/** ID of the current tool — passed to ToolDirectory to suppress its own link */
	current: string
	/** npm package version (imported from root package.json) */
	npmVersion: string
	/** site version (imported from site/package.json) */
	siteVersion: string
}

const GA_ID = "G-L6M7RYHFLG"

/** Shared footer: tool directory grid, Liiift link, version numbers, GA4 analytics, and cookie consent. */
export default function SiteFooter({ current, npmVersion, siteVersion }: SiteFooterProps) {
	return (
		<footer className="w-full max-w-2xl lg:max-w-5xl flex flex-col gap-6 pt-8 border-t border-foreground/10 text-xs">
			{/*
			 * GA4 Consent Mode v2: defaults to denied, restores stored choice, then loads GA4.
			 * Single script ensures consent is set before the external library initialises.
			 */}
			<Script id="tooltip-init" strategy="afterInteractive">{`
				(function(){
					var tip=document.createElement('div');
					tip.style.cssText='position:fixed;z-index:9999;pointer-events:none;background:rgba(0,0,0,0.75);color:#fff;font-size:11px;line-height:1.4;padding:5px 8px;border-radius:4px;border:1px solid rgba(255,255,255,0.15);max-width:220px;opacity:0;transition:opacity 0.12s ease;white-space:normal;backdrop-filter:blur(4px);';
					document.body.appendChild(tip);
					var timer=null,current=null,stored=null;
					function show(el){
						var rect=el.getBoundingClientRect();
						var label=el.getAttribute('data-tip')||el.getAttribute('title')||'';
						if(!label)return;
						tip.textContent=label;
						tip.style.opacity='0';
						tip.style.display='block';
						var tw=tip.offsetWidth,th=tip.offsetHeight;
						var cx=rect.left+rect.width/2;
						var top=rect.top-th-8;
						if(top<8){top=rect.bottom+8;}
						var left=cx-tw/2;
						if(left<8)left=8;
						if(left+tw>window.innerWidth-8)left=window.innerWidth-8-tw;
						tip.style.left=left+'px';
						tip.style.top=top+'px';
						tip.style.opacity='1';
					}
					function hide(){
						clearTimeout(timer);
						tip.style.opacity='0';
						if(current&&stored!==null){current.setAttribute('title',stored);stored=null;}
						current=null;
					}
					document.addEventListener('mouseover',function(e){
						var el=e.target&&e.target.closest('button[title],input[title]');
						if(!el||el===current)return;
						hide();
						current=el;
						stored=el.getAttribute('title');
						el.setAttribute('data-tip',stored);
						el.removeAttribute('title');
						timer=setTimeout(function(){show(el);},220);
					});
					document.addEventListener('mouseout',function(e){
						if(!current)return;
						var to=e.relatedTarget;
						if(to&&to===current)return;
						hide();
					});
					window.addEventListener('scroll',hide,{passive:true,capture:true});
				})();
			`}</Script>
			<Script id="ga-init" strategy="afterInteractive">{`
				window.dataLayer=window.dataLayer||[];
				function gtag(){dataLayer.push(arguments)}
				gtag('consent','default',{analytics_storage:'denied',wait_for_update:10000});
				try{if(localStorage.getItem('cookie-consent')==='granted'){gtag('consent','update',{analytics_storage:'granted'})}}catch(e){}
				(function(){var s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id=${GA_ID}';document.head.appendChild(s)})();
				gtag('js',new Date());
				gtag('config','${GA_ID}')
			`}</Script>
			<Script src="/_vercel/insights/script.js" strategy="afterInteractive" />
			<ToolDirectory current={current} />
			<hr className="border-foreground/10" />
			<div className="grid grid-cols-2 sm:grid-cols-4 gap-x-8 text-muted">
				<a
					href="https://overpunch.ca"
					target="_blank"
					rel="noopener noreferrer"
					aria-label="Liiift Studio"
					className="w-fit -mx-2 px-2 py-1 rounded hover:bg-foreground/10 transition-colors"
				>
					{/* Logo recoloured via CSS mask so it inherits the foreground colour —
					    light on dark-background tools, dark on light-background tools. */}
					<span
						aria-hidden="true"
						className="block h-4 w-[27px] opacity-60 hover:opacity-100 transition-opacity"
						style={{
							backgroundColor: "currentColor",
							WebkitMaskImage: "url(/logo-white.png)",
							maskImage: "url(/logo-white.png)",
							WebkitMaskRepeat: "no-repeat",
							maskRepeat: "no-repeat",
							WebkitMaskSize: "contain",
							maskSize: "contain",
							WebkitMaskPosition: "left center",
							maskPosition: "left center",
						}}
					/>
				</a>
				<span className="sm:col-start-4 tabular-nums">
					npm v{npmVersion} · site v{siteVersion}
				</span>
			</div>
			<CookieBanner />
		</footer>
	)
}
